/* eslint-disable dot-notation */
import gameTitlesData from './gameTitlesData.js';
import platformsData from './platformsData.js';

const gameTitlesMap = Object.fromEntries(gameTitlesData.map((g) => [g.title, g._id]));
const platformsMap = Object.fromEntries(platformsData.map((p) => [p.name, p._id]));

const productsData = [
  {
    gameTitle_id: gameTitlesMap['Elden Ring'],
    platform_id: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Elden Ring'],
    platform_id: platformsMap['PlayStation5'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Elden Ring'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['God of War Ragnarök'],
    platform_id: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['God of War Ragnarök'],
    platform_id: platformsMap['PlayStation5'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Sekiro'],
    platform_id: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Sekiro'],
    platform_id: platformsMap['PlayStation5'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Resident Evil 4 Remake'],
    platform_id: platformsMap['PlayStation5'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Resident Evil 4 Remake'],
    platform_id: platformsMap['XBoxSeries'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Resident Evil 4 Remake'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Resident Evil 2 Remake'],
    platform_id: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Resident Evil 2 Remake'],
    platform_id: platformsMap['XBoxOne'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Resident Evil 2 Remake'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Metroid Prime Remastered'],
    platform_id: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['PAC-MAN 256'],
    platform_id: platformsMap['PC'],
    stock: 100,
    listedDate: '2020-01-01',
    price: 20,
  },
  {
    gameTitle_id: gameTitlesMap['Tetris Ultimate'],
    platform_id: platformsMap['NintendoSwitch'],
    stock: 100,
    listedDate: '2020-01-01',
    price: 20,
  },
  {
    gameTitle_id: gameTitlesMap['Tetris Ultimate'],
    platform_id: platformsMap['PC'],
    stock: 100,
    listedDate: '2020-01-01',
    price: 20,
  },
  {
    gameTitle_id: gameTitlesMap['Arkanoid'],
    platform_id: platformsMap['PC'],
    stock: 100,
    listedDate: '2020-01-01',
    price: 20,
  },
  {
    gameTitle_id: gameTitlesMap['Space Invaders'],
    platform_id: platformsMap['PC'],
    stock: 100,
    listedDate: '2020-01-01',
    price: 20,
  },
  {
    gameTitle_id: gameTitlesMap['Golf it!'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['FIFA Manager 13'],
    platform_id: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['FIFA Manager 13'],
    platform_id: platformsMap['XBoxOne'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Tony Hawk\'s Pro Skater 1+2'],
    platform_id: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Tony Hawk\'s Pro Skater 1+2'],
    platform_id: platformsMap['XBoxOne'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Rocket League'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Rocket League'],
    platform_id: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Yu-Gi-Oh! Legacy of the Duelist'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Total War: Warhammer 3'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Mario + Rabbids: Sparks of Hope'],
    platform_id: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Age of Empires 4'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Monopoly'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Monopoly'],
    platform_id: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Monopoly'],
    platform_id: platformsMap['PlayStation5'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Monopoly'],
    platform_id: platformsMap['XBoxOne'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Monopoly'],
    platform_id: platformsMap['XBoxSeries'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Euro Truck Simulator'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Goat Simulator'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Goat Simulator'],
    platform_id: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Goat Simulator'],
    platform_id: platformsMap['XBoxOne'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Microsoft Flight Simulator X'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Microsoft Flight Simulator X'],
    platform_id: platformsMap['XBoxOne'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Microsoft Flight Simulator X'],
    platform_id: platformsMap['XBoxSeries'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Duck Hunt'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Just Dance 2020'],
    platform_id: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Just Dance 2020'],
    platform_id: platformsMap['PlayStation5'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Just Dance 2020'],
    platform_id: platformsMap['XBoxOne'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Just Dance 2020'],
    platform_id: platformsMap['XBoxSeries'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Just Dance 2020'],
    platform_id: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Hanna Montana Music Jam'],
    platform_id: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Guitar Hero 2'],
    platform_id: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Guitar Hero 2'],
    platform_id: platformsMap['PlayStation5'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Street Fighter 6'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Tekken'],
    platform_id: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Super Smash Bros Melee'],
    platform_id: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Mortal Kombat 11'],
    platform_id: platformsMap['XBoxOne'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['F1 2012'],
    platform_id: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Crash Team Racing Nitro-Fueled'],
    platform_id: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Need for Speed: Underground 2'],
    platform_id: platformsMap['XBoxOne'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Ori and the Will of the Wisps'],
    platform_id: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Ori and the Will of the Wisps'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Ori and the Blind Forest'],
    platform_id: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Ori and the Blind Forest'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['It takes two'],
    platform_id: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Cuphead'],
    platform_id: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Baldur\'s Gate 3'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Baldur\'s Gate 3'],
    platform_id: platformsMap['PlayStation5'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Baldur\'s Gate 3'],
    platform_id: platformsMap['XBoxSeries'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Final Fantasy X'],
    platform_id: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Quake'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Doom Eternal'],
    platform_id: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Alan Wake 2'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Phasmophobia'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Amnesia Collection'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Metal Gear Solid 3: Snake Eater'],
    platform_id: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Assassin\'s Creed Odyssey'],
    platform_id: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Splinter Cell: Chaos Theory'],
    platform_id: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['The Walking Dead: The Telltale'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Detroit Become Human'],
    platform_id: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Twelve Minutes'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['The Talos Principle'],
    platform_id: platformsMap['XBoxOne'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['The Talos Principle 2'],
    platform_id: platformsMap['XBoxSeries'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Portal 2'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Little Nightmares I & II'],
    platform_id: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Minecraft'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Terraria'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Grand Theft Auto V'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Grand Theft Auto V'],
    platform_id: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Grand Theft Auto V'],
    platform_id: platformsMap['PlayStation5'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Red Dead Redemption 2'],
    platform_id: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Red Dead Redemption 2'],
    platform_id: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle_id: gameTitlesMap['Red Dead Redemption 2'],
    platform_id: platformsMap['PlayStation5'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
];

export default productsData;
