/* eslint-disable dot-notation */
import mongoose from 'mongoose';
import gameTitlesData from './gameTitlesData.js';
import platformsData from './platformsData.js';

const { ObjectId } = mongoose.Types;
const gameTitlesMap = Object.fromEntries(gameTitlesData.map((g) => [g.title, g._id]));
const platformsMap = Object.fromEntries(platformsData.map((p) => [p.name, p._id]));

/**
 * I'm hardcoding the id's of some products so I can
 * hardcode the same id's on some orders, for simplicity
 * of the seeding script
 * 65c092e67aaecf4937ffad34 first EldenRing
 * 65c092e67aaecf4937ffad37 first God of War
 * 65c092e67aaecf4937ffad41 first Metroid Prime
 */

const productsData = [
  {
    _id: new ObjectId('65c092e67aaecf4937ffad34'), // HARDCODED
    gameTitle: gameTitlesMap['Elden Ring'],
    platform: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Elden Ring'],
    platform: platformsMap['PlayStation5'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Elden Ring'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    _id: new ObjectId('65c092e67aaecf4937ffad37'), // HARDCODED
    gameTitle: gameTitlesMap['God of War Ragnarök'],
    platform: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['God of War Ragnarök'],
    platform: platformsMap['PlayStation5'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Sekiro'],
    platform: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Sekiro'],
    platform: platformsMap['PlayStation5'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Resident Evil 4 Remake'],
    platform: platformsMap['PlayStation5'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Resident Evil 4 Remake'],
    platform: platformsMap['XBoxSeries'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Resident Evil 4 Remake'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Resident Evil 2 Remake'],
    platform: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Resident Evil 2 Remake'],
    platform: platformsMap['XBoxOne'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Resident Evil 2 Remake'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    _id: new ObjectId('65c092e67aaecf4937ffad41'), // HARDCODED
    gameTitle: gameTitlesMap['Metroid Prime Remastered'],
    platform: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['PAC-MAN 256'],
    platform: platformsMap['PC'],
    stock: 100,
    listedDate: '2020-01-01',
    price: 20,
  },
  {
    gameTitle: gameTitlesMap['Tetris Ultimate'],
    platform: platformsMap['NintendoSwitch'],
    stock: 100,
    listedDate: '2020-01-01',
    price: 20,
  },
  {
    gameTitle: gameTitlesMap['Tetris Ultimate'],
    platform: platformsMap['PC'],
    stock: 100,
    listedDate: '2020-01-01',
    price: 20,
  },
  {
    gameTitle: gameTitlesMap['Arkanoid'],
    platform: platformsMap['PC'],
    stock: 100,
    listedDate: '2020-01-01',
    price: 20,
  },
  {
    gameTitle: gameTitlesMap['Space Invaders'],
    platform: platformsMap['PC'],
    stock: 100,
    listedDate: '2020-01-01',
    price: 20,
  },
  {
    gameTitle: gameTitlesMap['Golf it!'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['FIFA Manager 13'],
    platform: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['FIFA Manager 13'],
    platform: platformsMap['XBoxOne'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Tony Hawk\'s Pro Skater 1+2'],
    platform: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Tony Hawk\'s Pro Skater 1+2'],
    platform: platformsMap['XBoxOne'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Rocket League'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Rocket League'],
    platform: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Yu-Gi-Oh! Legacy of the Duelist'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Total War: Warhammer 3'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Mario + Rabbids: Sparks of Hope'],
    platform: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Age of Empires 4'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Monopoly'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Monopoly'],
    platform: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Monopoly'],
    platform: platformsMap['PlayStation5'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Monopoly'],
    platform: platformsMap['XBoxOne'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Monopoly'],
    platform: platformsMap['XBoxSeries'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Euro Truck Simulator'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Goat Simulator'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Goat Simulator'],
    platform: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Goat Simulator'],
    platform: platformsMap['XBoxOne'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Microsoft Flight Simulator X'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Microsoft Flight Simulator X'],
    platform: platformsMap['XBoxOne'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Microsoft Flight Simulator X'],
    platform: platformsMap['XBoxSeries'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Duck Hunt'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Just Dance 2020'],
    platform: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Just Dance 2020'],
    platform: platformsMap['PlayStation5'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Just Dance 2020'],
    platform: platformsMap['XBoxOne'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Just Dance 2020'],
    platform: platformsMap['XBoxSeries'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Just Dance 2020'],
    platform: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Hanna Montana Music Jam'],
    platform: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Guitar Hero 2'],
    platform: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Guitar Hero 2'],
    platform: platformsMap['PlayStation5'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Street Fighter 6'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Tekken'],
    platform: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Super Smash Bros Melee'],
    platform: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Mortal Kombat 11'],
    platform: platformsMap['XBoxOne'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['F1 2012'],
    platform: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Crash Team Racing Nitro-Fueled'],
    platform: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Need for Speed: Underground 2'],
    platform: platformsMap['XBoxOne'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Ori and the Will of the Wisps'],
    platform: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Ori and the Will of the Wisps'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Ori and the Blind Forest'],
    platform: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Ori and the Blind Forest'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['It takes two'],
    platform: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Cuphead'],
    platform: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Baldur\'s Gate 3'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Baldur\'s Gate 3'],
    platform: platformsMap['PlayStation5'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Baldur\'s Gate 3'],
    platform: platformsMap['XBoxSeries'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Final Fantasy X'],
    platform: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Quake'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Doom Eternal'],
    platform: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Alan Wake 2'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Phasmophobia'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Amnesia Collection'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Metal Gear Solid 3: Snake Eater'],
    platform: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Assassin\'s Creed Odyssey'],
    platform: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Splinter Cell: Chaos Theory'],
    platform: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['The Walking Dead: The Telltale'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Detroit Become Human'],
    platform: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Twelve Minutes'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['The Talos Principle'],
    platform: platformsMap['XBoxOne'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['The Talos Principle 2'],
    platform: platformsMap['XBoxSeries'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Portal 2'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Little Nightmares I & II'],
    platform: platformsMap['NintendoSwitch'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Minecraft'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Terraria'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Grand Theft Auto V'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Grand Theft Auto V'],
    platform: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Grand Theft Auto V'],
    platform: platformsMap['PlayStation5'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Red Dead Redemption 2'],
    platform: platformsMap['PC'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Red Dead Redemption 2'],
    platform: platformsMap['PlayStation4'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
  {
    gameTitle: gameTitlesMap['Red Dead Redemption 2'],
    platform: platformsMap['PlayStation5'],
    stock: 5,
    listedDate: '2020-01-01',
    price: 50,
  },
];

export default productsData;
